//
//  Bg_0.swift
//  ProjectName
//
//  Created by AuthorName on 2019/4/22.
//  Copyright © 2019 CompanyName. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class Bg_0 : NSObject {
    
    //// Drawing Methods
    
    @objc dynamic public class func drawCanvas1(frame targetFrame: CGRect = CGRect(x: 0, y: 0, width: 410, height: 893), resizing: ResizingBehavior = .aspectFit) {
        //// General Declarations
        let context = UIGraphicsGetCurrentContext()!
        
        //// Resize to Target Frame
        context.saveGState()
        let resizedFrame: CGRect = resizing.apply(rect: CGRect(x: 0, y: 0, width: 410, height: 893), target: targetFrame)
        context.translateBy(x: resizedFrame.minX, y: resizedFrame.minY)
        context.scaleBy(x: resizedFrame.width / 410, y: resizedFrame.height / 893)
        
        
        //// Color Declarations
        let fillColor = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)
        let fillColor2 = UIColor(red: 0.525, green: 0.525, blue: 0.525, alpha: 1.000)
        let fillColor3 = UIColor(red: 0.769, green: 0.769, blue: 0.769, alpha: 1.000)
        let fillColor4 = UIColor(red: 0.557, green: 0.557, blue: 0.557, alpha: 1.000)
        let fillColor5 = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)
        let fillColor6 = UIColor(red: 0.294, green: 0.294, blue: 0.294, alpha: 1.000)
        let fillColor7 = UIColor(red: 0.808, green: 0.808, blue: 0.808, alpha: 1.000)
        let fillColor8 = UIColor(red: 0.729, green: 0.729, blue: 0.729, alpha: 1.000)
        let fillColor9 = UIColor(red: 0.318, green: 0.318, blue: 0.318, alpha: 1.000)
        let fillColor10 = UIColor(red: 0.451, green: 0.451, blue: 0.451, alpha: 1.000)
        let fillColor11 = UIColor(red: 0.494, green: 0.494, blue: 0.494, alpha: 1.000)
        let fillColor12 = UIColor(red: 0.173, green: 0.173, blue: 0.173, alpha: 1.000)
        let fillColor13 = UIColor(red: 0.588, green: 0.588, blue: 0.588, alpha: 1.000)
        let fillColor14 = UIColor(red: 0.224, green: 0.224, blue: 0.224, alpha: 1.000)
        let fillColor15 = UIColor(red: 0.757, green: 0.757, blue: 0.757, alpha: 1.000)
        let fillColor16 = UIColor(red: 0.667, green: 0.667, blue: 0.667, alpha: 1.000)
        let fillColor17 = UIColor(red: 0.647, green: 0.647, blue: 0.647, alpha: 1.000)
        let fillColor18 = UIColor(red: 0.682, green: 0.682, blue: 0.682, alpha: 1.000)
        let fillColor19 = UIColor(red: 0.259, green: 0.259, blue: 0.259, alpha: 1.000)
        let fillColor20 = UIColor(red: 0.086, green: 0.086, blue: 0.086, alpha: 1.000)
        let fillColor21 = UIColor(red: 0.812, green: 0.812, blue: 0.812, alpha: 1.000)
        let fillColor22 = UIColor(red: 0.706, green: 0.706, blue: 0.706, alpha: 1.000)
        let fillColor23 = UIColor(red: 0.047, green: 0.047, blue: 0.047, alpha: 1.000)
        let fillColor24 = UIColor(red: 0.467, green: 0.467, blue: 0.467, alpha: 1.000)
        let fillColor25 = UIColor(red: 0.624, green: 0.624, blue: 0.624, alpha: 1.000)
        let fillColor26 = UIColor(red: 0.855, green: 0.855, blue: 0.855, alpha: 1.000)
        let fillColor27 = UIColor(red: 0.412, green: 0.412, blue: 0.412, alpha: 1.000)
        let fillColor28 = UIColor(red: 0.373, green: 0.373, blue: 0.373, alpha: 1.000)
        let fillColor29 = UIColor(red: 0.843, green: 0.843, blue: 0.843, alpha: 1.000)
        let fillColor30 = UIColor(red: 0.353, green: 0.353, blue: 0.353, alpha: 1.000)
        let fillColor31 = UIColor(red: 0.149, green: 0.149, blue: 0.149, alpha: 1.000)
        
        //// bg_0.svg Group
        //// Rectangle Drawing
        let rectanglePath = UIBezierPath(rect: CGRect(x: 0, y: 0, width: 410, height: 893))
        fillColor.setFill()
        rectanglePath.fill()
        
        
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: 195.24, y: 483.29))
        bezierPath.addCurve(to: CGPoint(x: 202.56, y: 486.27), controlPoint1: CGPoint(x: 198.28, y: 485.33), controlPoint2: CGPoint(x: 199.02, y: 485.53))
        bezierPath.addCurve(to: CGPoint(x: 195.24, y: 483.29), controlPoint1: CGPoint(x: 199.51, y: 484.23), controlPoint2: CGPoint(x: 198.78, y: 484.04))
        bezierPath.close()
        fillColor2.setFill()
        bezierPath.fill()
        
        
        //// Bezier 2 Drawing
        let bezier2Path = UIBezierPath()
        bezier2Path.move(to: CGPoint(x: 202.56, y: 483.29))
        bezier2Path.addLine(to: CGPoint(x: 205, y: 486.27))
        bezier2Path.addLine(to: CGPoint(x: 202.56, y: 483.29))
        bezier2Path.close()
        fillColor3.setFill()
        bezier2Path.fill()
        
        
        //// Bezier 3 Drawing
        let bezier3Path = UIBezierPath()
        bezier3Path.move(to: CGPoint(x: 190.36, y: 486.27))
        bezier3Path.addLine(to: CGPoint(x: 192.8, y: 489.26))
        bezier3Path.addLine(to: CGPoint(x: 190.36, y: 486.27))
        bezier3Path.close()
        fillColor4.setFill()
        bezier3Path.fill()
        
        
        //// Bezier 4 Drawing
        let bezier4Path = UIBezierPath()
        bezier4Path.move(to: CGPoint(x: 187.92, y: 495.22))
        bezier4Path.addCurve(to: CGPoint(x: 205, y: 489.26), controlPoint1: CGPoint(x: 193.77, y: 492.16), controlPoint2: CGPoint(x: 198.69, y: 490.22))
        bezier4Path.addCurve(to: CGPoint(x: 187.92, y: 495.22), controlPoint1: CGPoint(x: 197.43, y: 485.77), controlPoint2: CGPoint(x: 193.41, y: 488.36))
        bezier4Path.close()
        fillColor5.setFill()
        bezier4Path.fill()
        
        
        //// Bezier 5 Drawing
        let bezier5Path = UIBezierPath()
        bezier5Path.move(to: CGPoint(x: 205.81, y: 488.26))
        bezier5Path.addCurve(to: CGPoint(x: 206.63, y: 490.25), controlPoint1: CGPoint(x: 205.68, y: 488.43), controlPoint2: CGPoint(x: 205.54, y: 491.58))
        bezier5Path.addCurve(to: CGPoint(x: 205.81, y: 488.26), controlPoint1: CGPoint(x: 206.76, y: 490.09), controlPoint2: CGPoint(x: 206.9, y: 486.94))
        bezier5Path.close()
        fillColor6.setFill()
        bezier5Path.fill()
        
        
        //// Bezier 6 Drawing
        let bezier6Path = UIBezierPath()
        bezier6Path.move(to: CGPoint(x: 207.44, y: 486.27))
        bezier6Path.addLine(to: CGPoint(x: 209.88, y: 489.26))
        bezier6Path.addLine(to: CGPoint(x: 207.44, y: 486.27))
        bezier6Path.close()
        fillColor7.setFill()
        bezier6Path.fill()
        
        
        //// Bezier 7 Drawing
        let bezier7Path = UIBezierPath()
        bezier7Path.move(to: CGPoint(x: 219.64, y: 486.27))
        bezier7Path.addLine(to: CGPoint(x: 222.08, y: 489.26))
        bezier7Path.addLine(to: CGPoint(x: 219.64, y: 486.27))
        bezier7Path.close()
        fillColor8.setFill()
        bezier7Path.fill()
        
        
        //// Bezier 8 Drawing
        let bezier8Path = UIBezierPath()
        bezier8Path.move(to: CGPoint(x: 222.9, y: 488.26))
        bezier8Path.addCurve(to: CGPoint(x: 223.71, y: 490.25), controlPoint1: CGPoint(x: 222.76, y: 488.43), controlPoint2: CGPoint(x: 222.63, y: 491.58))
        bezier8Path.addCurve(to: CGPoint(x: 222.9, y: 488.26), controlPoint1: CGPoint(x: 223.85, y: 490.09), controlPoint2: CGPoint(x: 223.98, y: 486.94))
        bezier8Path.close()
        fillColor9.setFill()
        bezier8Path.fill()
        
        
        //// Bezier 9 Drawing
        let bezier9Path = UIBezierPath()
        bezier9Path.move(to: CGPoint(x: 224.52, y: 486.27))
        bezier9Path.addCurve(to: CGPoint(x: 231.85, y: 489.26), controlPoint1: CGPoint(x: 227.57, y: 488.32), controlPoint2: CGPoint(x: 228.3, y: 488.51))
        bezier9Path.addCurve(to: CGPoint(x: 224.52, y: 486.27), controlPoint1: CGPoint(x: 228.8, y: 487.21), controlPoint2: CGPoint(x: 228.07, y: 487.02))
        bezier9Path.close()
        fillColor5.setFill()
        bezier9Path.fill()
        
        
        //// Bezier 10 Drawing
        let bezier10Path = UIBezierPath()
        bezier10Path.move(to: CGPoint(x: 231.85, y: 486.27))
        bezier10Path.addLine(to: CGPoint(x: 234.29, y: 489.26))
        bezier10Path.addLine(to: CGPoint(x: 231.85, y: 486.27))
        bezier10Path.close()
        fillColor10.setFill()
        bezier10Path.fill()
        
        
        //// Bezier 11 Drawing
        let bezier11Path = UIBezierPath()
        bezier11Path.move(to: CGPoint(x: 187.92, y: 489.26))
        bezier11Path.addLine(to: CGPoint(x: 190.36, y: 492.24))
        bezier11Path.addLine(to: CGPoint(x: 187.92, y: 489.26))
        bezier11Path.close()
        fillColor11.setFill()
        bezier11Path.fill()
        
        
        //// Bezier 12 Drawing
        let bezier12Path = UIBezierPath()
        bezier12Path.move(to: CGPoint(x: 192.8, y: 489.26))
        bezier12Path.addLine(to: CGPoint(x: 195.24, y: 492.24))
        bezier12Path.addLine(to: CGPoint(x: 192.8, y: 489.26))
        bezier12Path.close()
        fillColor12.setFill()
        bezier12Path.fill()
        
        
        //// Bezier 13 Drawing
        let bezier13Path = UIBezierPath()
        bezier13Path.move(to: CGPoint(x: 195.24, y: 489.26))
        bezier13Path.addLine(to: CGPoint(x: 197.68, y: 492.24))
        bezier13Path.addLine(to: CGPoint(x: 195.24, y: 489.26))
        bezier13Path.close()
        fillColor13.setFill()
        bezier13Path.fill()
        
        
        //// Bezier 14 Drawing
        let bezier14Path = UIBezierPath()
        bezier14Path.move(to: CGPoint(x: 197.68, y: 489.26))
        bezier14Path.addCurve(to: CGPoint(x: 205, y: 492.24), controlPoint1: CGPoint(x: 200.73, y: 491.3), controlPoint2: CGPoint(x: 201.46, y: 491.49))
        bezier14Path.addCurve(to: CGPoint(x: 197.68, y: 489.26), controlPoint1: CGPoint(x: 201.95, y: 490.2), controlPoint2: CGPoint(x: 201.22, y: 490.01))
        bezier14Path.close()
        fillColor3.setFill()
        bezier14Path.fill()
        
        
        //// Bezier 15 Drawing
        let bezier15Path = UIBezierPath()
        bezier15Path.move(to: CGPoint(x: 207.44, y: 489.26))
        bezier15Path.addCurve(to: CGPoint(x: 212.32, y: 495.22), controlPoint1: CGPoint(x: 208.77, y: 494.14), controlPoint2: CGPoint(x: 208.33, y: 493.6))
        bezier15Path.addCurve(to: CGPoint(x: 207.44, y: 489.26), controlPoint1: CGPoint(x: 210.99, y: 490.35), controlPoint2: CGPoint(x: 211.43, y: 490.88))
        bezier15Path.close()
        fillColor5.setFill()
        bezier15Path.fill()
        
        
        //// Bezier 16 Drawing
        let bezier16Path = UIBezierPath()
        bezier16Path.move(to: CGPoint(x: 209.88, y: 489.26))
        bezier16Path.addLine(to: CGPoint(x: 212.32, y: 492.24))
        bezier16Path.addLine(to: CGPoint(x: 209.88, y: 489.26))
        bezier16Path.close()
        fillColor2.setFill()
        bezier16Path.fill()
        
        
        //// Bezier 17 Drawing
        let bezier17Path = UIBezierPath()
        bezier17Path.move(to: CGPoint(x: 218.02, y: 491.25))
        bezier17Path.addCurve(to: CGPoint(x: 218.83, y: 493.23), controlPoint1: CGPoint(x: 217.88, y: 491.41), controlPoint2: CGPoint(x: 217.74, y: 494.56))
        bezier17Path.addCurve(to: CGPoint(x: 218.02, y: 491.25), controlPoint1: CGPoint(x: 218.97, y: 493.07), controlPoint2: CGPoint(x: 219.1, y: 489.92))
        bezier17Path.close()
        fillColor14.setFill()
        bezier17Path.fill()
        
        
        //// Bezier 18 Drawing
        let bezier18Path = UIBezierPath()
        bezier18Path.move(to: CGPoint(x: 219.64, y: 489.26))
        bezier18Path.addLine(to: CGPoint(x: 222.08, y: 492.24))
        bezier18Path.addLine(to: CGPoint(x: 219.64, y: 489.26))
        bezier18Path.close()
        fillColor5.setFill()
        bezier18Path.fill()
        
        
        //// Bezier 19 Drawing
        let bezier19Path = UIBezierPath()
        bezier19Path.move(to: CGPoint(x: 224.52, y: 489.26))
        bezier19Path.addCurve(to: CGPoint(x: 231.85, y: 492.24), controlPoint1: CGPoint(x: 227.57, y: 491.3), controlPoint2: CGPoint(x: 228.3, y: 491.49))
        bezier19Path.addCurve(to: CGPoint(x: 224.52, y: 489.26), controlPoint1: CGPoint(x: 228.8, y: 490.2), controlPoint2: CGPoint(x: 228.07, y: 490.01))
        bezier19Path.close()
        fillColor15.setFill()
        bezier19Path.fill()
        
        
        //// Bezier 20 Drawing
        let bezier20Path = UIBezierPath()
        bezier20Path.move(to: CGPoint(x: 231.85, y: 489.26))
        bezier20Path.addLine(to: CGPoint(x: 234.29, y: 492.24))
        bezier20Path.addLine(to: CGPoint(x: 231.85, y: 489.26))
        bezier20Path.close()
        fillColor14.setFill()
        bezier20Path.fill()
        
        
        //// Bezier 21 Drawing
        let bezier21Path = UIBezierPath()
        bezier21Path.move(to: CGPoint(x: 234.29, y: 489.26))
        bezier21Path.addCurve(to: CGPoint(x: 234.29, y: 528.04), controlPoint1: CGPoint(x: 240.6, y: 504.7), controlPoint2: CGPoint(x: 240.6, y: 512.6))
        bezier21Path.addCurve(to: CGPoint(x: 234.29, y: 489.26), controlPoint1: CGPoint(x: 245.6, y: 515.83), controlPoint2: CGPoint(x: 245.6, y: 501.47))
        bezier21Path.close()
        fillColor5.setFill()
        bezier21Path.fill()
        
        
        //// Bezier 22 Drawing
        let bezier22Path = UIBezierPath()
        bezier22Path.move(to: CGPoint(x: 236.73, y: 489.26))
        bezier22Path.addLine(to: CGPoint(x: 239.17, y: 492.24))
        bezier22Path.addLine(to: CGPoint(x: 236.73, y: 489.26))
        bezier22Path.close()
        fillColor16.setFill()
        bezier22Path.fill()
        
        
        //// Bezier 23 Drawing
        let bezier23Path = UIBezierPath()
        bezier23Path.move(to: CGPoint(x: 185.48, y: 492.24))
        bezier23Path.addLine(to: CGPoint(x: 187.92, y: 495.22))
        bezier23Path.addLine(to: CGPoint(x: 185.48, y: 492.24))
        bezier23Path.close()
        fillColor17.setFill()
        bezier23Path.fill()
        
        
        //// Bezier 24 Drawing
        let bezier24Path = UIBezierPath()
        bezier24Path.move(to: CGPoint(x: 190.36, y: 492.24))
        bezier24Path.addLine(to: CGPoint(x: 192.8, y: 495.22))
        bezier24Path.addLine(to: CGPoint(x: 190.36, y: 492.24))
        bezier24Path.close()
        fillColor11.setFill()
        bezier24Path.fill()
        
        
        //// Bezier 25 Drawing
        let bezier25Path = UIBezierPath()
        bezier25Path.move(to: CGPoint(x: 217.2, y: 495.22))
        bezier25Path.addCurve(to: CGPoint(x: 219.06, y: 512.64), controlPoint1: CGPoint(x: 218.67, y: 500.63), controlPoint2: CGPoint(x: 221.17, y: 506.92))
        bezier25Path.addCurve(to: CGPoint(x: 207.39, y: 512.64), controlPoint1: CGPoint(x: 216.61, y: 519.3), controlPoint2: CGPoint(x: 208.95, y: 520.9))
        bezier25Path.addCurve(to: CGPoint(x: 209.88, y: 495.22), controlPoint1: CGPoint(x: 206.37, y: 507.27), controlPoint2: CGPoint(x: 208.82, y: 500.35))
        bezier25Path.addCurve(to: CGPoint(x: 209.88, y: 545.44), controlPoint1: CGPoint(x: 176.71, y: 483.71), controlPoint2: CGPoint(x: 186.07, y: 545.69))
        bezier25Path.addCurve(to: CGPoint(x: 217.2, y: 495.22), controlPoint1: CGPoint(x: 235.81, y: 545.17), controlPoint2: CGPoint(x: 253.5, y: 485.18))
        bezier25Path.close()
        fillColor.setFill()
        bezier25Path.fill()
        
        
        //// Bezier 26 Drawing
        let bezier26Path = UIBezierPath()
        bezier26Path.move(to: CGPoint(x: 207.44, y: 492.24))
        bezier26Path.addLine(to: CGPoint(x: 209.88, y: 495.22))
        bezier26Path.addLine(to: CGPoint(x: 207.44, y: 492.24))
        bezier26Path.close()
        fillColor18.setFill()
        bezier26Path.fill()
        
        
        //// Bezier 27 Drawing
        let bezier27Path = UIBezierPath()
        bezier27Path.move(to: CGPoint(x: 212.32, y: 492.24))
        bezier27Path.addLine(to: CGPoint(x: 214.76, y: 495.22))
        bezier27Path.addLine(to: CGPoint(x: 212.32, y: 492.24))
        bezier27Path.close()
        fillColor19.setFill()
        bezier27Path.fill()
        
        
        //// Bezier 28 Drawing
        let bezier28Path = UIBezierPath()
        bezier28Path.move(to: CGPoint(x: 214.76, y: 492.24))
        bezier28Path.addCurve(to: CGPoint(x: 214.76, y: 504.17), controlPoint1: CGPoint(x: 213.78, y: 498.04), controlPoint2: CGPoint(x: 213.78, y: 498.37))
        bezier28Path.addCurve(to: CGPoint(x: 214.76, y: 492.24), controlPoint1: CGPoint(x: 216.5, y: 498.93), controlPoint2: CGPoint(x: 216.5, y: 497.49))
        bezier28Path.close()
        fillColor20.setFill()
        bezier28Path.fill()
        
        
        //// Bezier 29 Drawing
        let bezier29Path = UIBezierPath()
        bezier29Path.move(to: CGPoint(x: 219.64, y: 492.24))
        bezier29Path.addLine(to: CGPoint(x: 222.08, y: 495.22))
        bezier29Path.addLine(to: CGPoint(x: 219.64, y: 492.24))
        bezier29Path.close()
        fillColor21.setFill()
        bezier29Path.fill()
        
        
        //// Bezier 30 Drawing
        let bezier30Path = UIBezierPath()
        bezier30Path.move(to: CGPoint(x: 234.29, y: 492.24))
        bezier30Path.addLine(to: CGPoint(x: 236.73, y: 495.22))
        bezier30Path.addLine(to: CGPoint(x: 234.29, y: 492.24))
        bezier30Path.close()
        fillColor13.setFill()
        bezier30Path.fill()
        
        
        //// Bezier 31 Drawing
        let bezier31Path = UIBezierPath()
        bezier31Path.move(to: CGPoint(x: 239.17, y: 492.24))
        bezier31Path.addLine(to: CGPoint(x: 241.61, y: 495.22))
        bezier31Path.addLine(to: CGPoint(x: 239.17, y: 492.24))
        bezier31Path.close()
        fillColor22.setFill()
        bezier31Path.fill()
        
        
        //// Bezier 32 Drawing
        let bezier32Path = UIBezierPath()
        bezier32Path.move(to: CGPoint(x: 186.29, y: 497.21))
        bezier32Path.addCurve(to: CGPoint(x: 187.1, y: 499.2), controlPoint1: CGPoint(x: 186.15, y: 497.38), controlPoint2: CGPoint(x: 186.02, y: 500.53))
        bezier32Path.addCurve(to: CGPoint(x: 186.29, y: 497.21), controlPoint1: CGPoint(x: 187.24, y: 499.04), controlPoint2: CGPoint(x: 187.37, y: 495.89))
        bezier32Path.close()
        fillColor23.setFill()
        bezier32Path.fill()
        
        
        //// Bezier 33 Drawing
        let bezier33Path = UIBezierPath()
        bezier33Path.move(to: CGPoint(x: 187.92, y: 495.22))
        bezier33Path.addLine(to: CGPoint(x: 190.36, y: 498.21))
        bezier33Path.addLine(to: CGPoint(x: 187.92, y: 495.22))
        bezier33Path.close()
        fillColor24.setFill()
        bezier33Path.fill()
        
        
        //// Bezier 34 Drawing
        let bezier34Path = UIBezierPath()
        bezier34Path.move(to: CGPoint(x: 209.88, y: 495.22))
        bezier34Path.addLine(to: CGPoint(x: 212.32, y: 498.21))
        bezier34Path.addLine(to: CGPoint(x: 209.88, y: 495.22))
        bezier34Path.close()
        fillColor25.setFill()
        bezier34Path.fill()
        
        
        //// Bezier 35 Drawing
        let bezier35Path = UIBezierPath()
        bezier35Path.move(to: CGPoint(x: 236.73, y: 495.22))
        bezier35Path.addLine(to: CGPoint(x: 239.17, y: 498.21))
        bezier35Path.addLine(to: CGPoint(x: 236.73, y: 495.22))
        bezier35Path.close()
        fillColor24.setFill()
        bezier35Path.fill()
        
        
        //// Bezier 36 Drawing
        let bezier36Path = UIBezierPath()
        bezier36Path.move(to: CGPoint(x: 183.04, y: 498.21))
        bezier36Path.addLine(to: CGPoint(x: 185.48, y: 501.19))
        bezier36Path.addLine(to: CGPoint(x: 183.04, y: 498.21))
        bezier36Path.close()
        fillColor2.setFill()
        bezier36Path.fill()
        
        
        //// Bezier 37 Drawing
        let bezier37Path = UIBezierPath()
        bezier37Path.move(to: CGPoint(x: 209.88, y: 498.21))
        bezier37Path.addLine(to: CGPoint(x: 212.32, y: 501.19))
        bezier37Path.addLine(to: CGPoint(x: 209.88, y: 498.21))
        bezier37Path.close()
        fillColor9.setFill()
        bezier37Path.fill()
        
        
        //// Bezier 38 Drawing
        let bezier38Path = UIBezierPath()
        bezier38Path.move(to: CGPoint(x: 217.2, y: 498.21))
        bezier38Path.addLine(to: CGPoint(x: 219.64, y: 501.19))
        bezier38Path.addLine(to: CGPoint(x: 217.2, y: 498.21))
        bezier38Path.close()
        fillColor8.setFill()
        bezier38Path.fill()
        
        
        //// Bezier 39 Drawing
        let bezier39Path = UIBezierPath()
        bezier39Path.move(to: CGPoint(x: 241.61, y: 498.21))
        bezier39Path.addLine(to: CGPoint(x: 244.05, y: 501.19))
        bezier39Path.addLine(to: CGPoint(x: 241.61, y: 498.21))
        bezier39Path.close()
        fillColor24.setFill()
        bezier39Path.fill()
        
        
        //// Bezier 40 Drawing
        let bezier40Path = UIBezierPath()
        bezier40Path.move(to: CGPoint(x: 183.04, y: 501.19))
        bezier40Path.addLine(to: CGPoint(x: 183.04, y: 513.12))
        bezier40Path.addCurve(to: CGPoint(x: 183.04, y: 501.19), controlPoint1: CGPoint(x: 184.77, y: 507.88), controlPoint2: CGPoint(x: 184.77, y: 506.44))
        bezier40Path.close()
        fillColor5.setFill()
        bezier40Path.fill()
        
        
        //// Bezier 41 Drawing
        let bezier41Path = UIBezierPath()
        bezier41Path.move(to: CGPoint(x: 185.48, y: 501.19))
        bezier41Path.addLine(to: CGPoint(x: 187.92, y: 504.17))
        bezier41Path.addLine(to: CGPoint(x: 185.48, y: 501.19))
        bezier41Path.close()
        fillColor4.setFill()
        bezier41Path.fill()
        
        
        //// Bezier 42 Drawing
        let bezier42Path = UIBezierPath()
        bezier42Path.move(to: CGPoint(x: 207.44, y: 501.19))
        bezier42Path.addLine(to: CGPoint(x: 209.88, y: 504.17))
        bezier42Path.addLine(to: CGPoint(x: 207.44, y: 501.19))
        bezier42Path.close()
        fillColor22.setFill()
        bezier42Path.fill()
        
        
        //// Bezier 43 Drawing
        let bezier43Path = UIBezierPath()
        bezier43Path.move(to: CGPoint(x: 209.88, y: 501.19))
        bezier43Path.addCurve(to: CGPoint(x: 207.44, y: 510.14), controlPoint1: CGPoint(x: 207.48, y: 505.6), controlPoint2: CGPoint(x: 207.44, y: 504.78))
        bezier43Path.addCurve(to: CGPoint(x: 209.88, y: 501.19), controlPoint1: CGPoint(x: 210.08, y: 506.01), controlPoint2: CGPoint(x: 210.35, y: 506.15))
        bezier43Path.close()
        fillColor5.setFill()
        bezier43Path.fill()
        
        
        //// Bezier 44 Drawing
        let bezier44Path = UIBezierPath()
        bezier44Path.move(to: CGPoint(x: 212.32, y: 501.19))
        bezier44Path.addLine(to: CGPoint(x: 209.88, y: 516.11))
        bezier44Path.addLine(to: CGPoint(x: 217.2, y: 516.11))
        bezier44Path.addCurve(to: CGPoint(x: 212.32, y: 501.19), controlPoint1: CGPoint(x: 216.26, y: 509.71), controlPoint2: CGPoint(x: 215.38, y: 506.41))
        bezier44Path.close()
        fillColor.setFill()
        bezier44Path.fill()
        
        
        //// Bezier 45 Drawing
        let bezier45Path = UIBezierPath()
        bezier45Path.move(to: CGPoint(x: 217.2, y: 501.19))
        bezier45Path.addLine(to: CGPoint(x: 217.2, y: 516.11))
        bezier45Path.addCurve(to: CGPoint(x: 217.2, y: 501.19), controlPoint1: CGPoint(x: 219.23, y: 510.05), controlPoint2: CGPoint(x: 219.23, y: 507.25))
        bezier45Path.close()
        fillColor5.setFill()
        bezier45Path.fill()
        
        
        //// Bezier 46 Drawing
        let bezier46Path = UIBezierPath()
        bezier46Path.move(to: CGPoint(x: 239.17, y: 501.19))
        bezier46Path.addLine(to: CGPoint(x: 241.61, y: 504.17))
        bezier46Path.addLine(to: CGPoint(x: 239.17, y: 501.19))
        bezier46Path.close()
        fillColor10.setFill()
        bezier46Path.fill()
        
        
        //// Bezier 47 Drawing
        let bezier47Path = UIBezierPath()
        bezier47Path.move(to: CGPoint(x: 185.48, y: 504.17))
        bezier47Path.addLine(to: CGPoint(x: 185.48, y: 513.12))
        bezier47Path.addCurve(to: CGPoint(x: 185.48, y: 504.17), controlPoint1: CGPoint(x: 187.18, y: 508.49), controlPoint2: CGPoint(x: 187.18, y: 508.81))
        bezier47Path.close()
        fillColor21.setFill()
        bezier47Path.fill()
        
        
        //// Bezier 48 Drawing
        let bezier48Path = UIBezierPath()
        bezier48Path.move(to: CGPoint(x: 209.88, y: 504.17))
        bezier48Path.addLine(to: CGPoint(x: 212.32, y: 507.16))
        bezier48Path.addLine(to: CGPoint(x: 209.88, y: 504.17))
        bezier48Path.close()
        fillColor16.setFill()
        bezier48Path.fill()
        
        
        //// Bezier 49 Drawing
        let bezier49Path = UIBezierPath()
        bezier49Path.move(to: CGPoint(x: 214.76, y: 504.17))
        bezier49Path.addLine(to: CGPoint(x: 217.2, y: 507.16))
        bezier49Path.addLine(to: CGPoint(x: 214.76, y: 504.17))
        bezier49Path.close()
        fillColor8.setFill()
        bezier49Path.fill()
        
        
        //// Bezier 50 Drawing
        let bezier50Path = UIBezierPath()
        bezier50Path.move(to: CGPoint(x: 219.64, y: 504.17))
        bezier50Path.addLine(to: CGPoint(x: 219.64, y: 516.11))
        bezier50Path.addCurve(to: CGPoint(x: 219.64, y: 504.17), controlPoint1: CGPoint(x: 221.38, y: 510.86), controlPoint2: CGPoint(x: 221.38, y: 509.42))
        bezier50Path.close()
        fillColor17.setFill()
        bezier50Path.fill()
        
        
        //// Bezier 51 Drawing
        let bezier51Path = UIBezierPath()
        bezier51Path.move(to: CGPoint(x: 239.17, y: 504.17))
        bezier51Path.addLine(to: CGPoint(x: 239.17, y: 513.12))
        bezier51Path.addCurve(to: CGPoint(x: 239.17, y: 504.17), controlPoint1: CGPoint(x: 240.87, y: 508.49), controlPoint2: CGPoint(x: 240.87, y: 508.81))
        bezier51Path.close()
        fillColor3.setFill()
        bezier51Path.fill()
        
        
        //// Bezier 52 Drawing
        let bezier52Path = UIBezierPath()
        bezier52Path.move(to: CGPoint(x: 244.86, y: 506.16))
        bezier52Path.addCurve(to: CGPoint(x: 245.68, y: 508.15), controlPoint1: CGPoint(x: 244.73, y: 506.33), controlPoint2: CGPoint(x: 244.59, y: 509.48))
        bezier52Path.addCurve(to: CGPoint(x: 244.86, y: 506.16), controlPoint1: CGPoint(x: 245.81, y: 507.99), controlPoint2: CGPoint(x: 245.95, y: 504.84))
        bezier52Path.close()
        fillColor26.setFill()
        bezier52Path.fill()
        
        
        //// Bezier 53 Drawing
        let bezier53Path = UIBezierPath()
        bezier53Path.move(to: CGPoint(x: 205, y: 507.16))
        bezier53Path.addLine(to: CGPoint(x: 207.44, y: 510.14))
        bezier53Path.addLine(to: CGPoint(x: 205, y: 507.16))
        bezier53Path.close()
        fillColor3.setFill()
        bezier53Path.fill()
        
        
        //// Rectangle 2 Drawing
        let rectangle2Path = UIBezierPath(rect: CGRect(x: 205, y: 520, width: 6, height: 6))
        fillColor27.setFill()
        rectangle2Path.fill()
        
        
        //// Bezier 54 Drawing
        let bezier54Path = UIBezierPath()
        bezier54Path.move(to: CGPoint(x: 183.04, y: 513.12))
        bezier54Path.addLine(to: CGPoint(x: 185.48, y: 516.11))
        bezier54Path.addLine(to: CGPoint(x: 183.04, y: 513.12))
        bezier54Path.close()
        fillColor12.setFill()
        bezier54Path.fill()
        
        
        //// Bezier 55 Drawing
        let bezier55Path = UIBezierPath()
        bezier55Path.move(to: CGPoint(x: 185.48, y: 513.12))
        bezier55Path.addLine(to: CGPoint(x: 187.92, y: 516.11))
        bezier55Path.addLine(to: CGPoint(x: 185.48, y: 513.12))
        bezier55Path.close()
        fillColor4.setFill()
        bezier55Path.fill()
        
        
        //// Bezier 56 Drawing
        let bezier56Path = UIBezierPath()
        bezier56Path.move(to: CGPoint(x: 239.17, y: 513.12))
        bezier56Path.addLine(to: CGPoint(x: 241.61, y: 516.11))
        bezier56Path.addLine(to: CGPoint(x: 239.17, y: 513.12))
        bezier56Path.close()
        bezier56Path.move(to: CGPoint(x: 184.66, y: 517.1))
        bezier56Path.addCurve(to: CGPoint(x: 186.29, y: 518.1), controlPoint1: CGPoint(x: 183.58, y: 518.43), controlPoint2: CGPoint(x: 186.15, y: 518.26))
        bezier56Path.addCurve(to: CGPoint(x: 184.66, y: 517.1), controlPoint1: CGPoint(x: 187.37, y: 516.77), controlPoint2: CGPoint(x: 184.8, y: 516.94))
        bezier56Path.close()
        fillColor28.setFill()
        bezier56Path.fill()
        
        
        //// Bezier 57 Drawing
        let bezier57Path = UIBezierPath()
        bezier57Path.move(to: CGPoint(x: 205, y: 516.11))
        bezier57Path.addLine(to: CGPoint(x: 207.44, y: 519.09))
        bezier57Path.addLine(to: CGPoint(x: 205, y: 516.11))
        bezier57Path.close()
        fillColor15.setFill()
        bezier57Path.fill()
        
        
        //// Bezier 58 Drawing
        let bezier58Path = UIBezierPath()
        bezier58Path.move(to: CGPoint(x: 207.44, y: 516.11))
        bezier58Path.addCurve(to: CGPoint(x: 214.76, y: 522.07), controlPoint1: CGPoint(x: 210.42, y: 519.67), controlPoint2: CGPoint(x: 210.91, y: 520.03))
        bezier58Path.addCurve(to: CGPoint(x: 207.44, y: 516.11), controlPoint1: CGPoint(x: 211.98, y: 519.05), controlPoint2: CGPoint(x: 210.83, y: 518.17))
        bezier58Path.close()
        fillColor5.setFill()
        bezier58Path.fill()
        
        
        //// Bezier 59 Drawing
        let bezier59Path = UIBezierPath()
        bezier59Path.move(to: CGPoint(x: 211.51, y: 517.1))
        bezier59Path.addCurve(to: CGPoint(x: 213.13, y: 518.1), controlPoint1: CGPoint(x: 210.42, y: 518.43), controlPoint2: CGPoint(x: 213, y: 518.26))
        bezier59Path.addCurve(to: CGPoint(x: 211.51, y: 517.1), controlPoint1: CGPoint(x: 214.22, y: 516.77), controlPoint2: CGPoint(x: 211.64, y: 516.94))
        bezier59Path.close()
        fillColor29.setFill()
        bezier59Path.fill()
        
        
        //// Bezier 60 Drawing
        let bezier60Path = UIBezierPath()
        bezier60Path.move(to: CGPoint(x: 214.76, y: 516.11))
        bezier60Path.addLine(to: CGPoint(x: 214.76, y: 522.07))
        bezier60Path.addCurve(to: CGPoint(x: 219.64, y: 516.11), controlPoint1: CGPoint(x: 218.75, y: 520.45), controlPoint2: CGPoint(x: 218.31, y: 520.98))
        bezier60Path.addLine(to: CGPoint(x: 214.76, y: 516.11))
        bezier60Path.close()
        fillColor14.setFill()
        bezier60Path.fill()
        
        
        //// Bezier 61 Drawing
        let bezier61Path = UIBezierPath()
        bezier61Path.move(to: CGPoint(x: 241.61, y: 516.11))
        bezier61Path.addLine(to: CGPoint(x: 244.05, y: 519.09))
        bezier61Path.addLine(to: CGPoint(x: 241.61, y: 516.11))
        bezier61Path.close()
        fillColor17.setFill()
        bezier61Path.fill()
        
        
        //// Bezier 62 Drawing
        let bezier62Path = UIBezierPath()
        bezier62Path.move(to: CGPoint(x: 183.04, y: 519.09))
        bezier62Path.addLine(to: CGPoint(x: 185.48, y: 522.07))
        bezier62Path.addLine(to: CGPoint(x: 183.04, y: 519.09))
        bezier62Path.close()
        fillColor18.setFill()
        bezier62Path.fill()
        
        
        //// Bezier 63 Drawing
        let bezier63Path = UIBezierPath()
        bezier63Path.move(to: CGPoint(x: 185.48, y: 519.09))
        bezier63Path.addCurve(to: CGPoint(x: 190.36, y: 534.01), controlPoint1: CGPoint(x: 186.81, y: 524.68), controlPoint2: CGPoint(x: 188.19, y: 528.8))
        bezier63Path.addCurve(to: CGPoint(x: 185.48, y: 519.09), controlPoint1: CGPoint(x: 190.44, y: 527.33), controlPoint2: CGPoint(x: 188.91, y: 524.33))
        bezier63Path.close()
        fillColor5.setFill()
        bezier63Path.fill()
        
        
        //// Bezier 64 Drawing
        let bezier64Path = UIBezierPath()
        bezier64Path.move(to: CGPoint(x: 207.44, y: 519.09))
        bezier64Path.addLine(to: CGPoint(x: 209.88, y: 522.07))
        bezier64Path.addLine(to: CGPoint(x: 207.44, y: 519.09))
        bezier64Path.close()
        fillColor4.setFill()
        bezier64Path.fill()
        
        
        //// Bezier 65 Drawing
        let bezier65Path = UIBezierPath()
        bezier65Path.move(to: CGPoint(x: 236.73, y: 519.09))
        bezier65Path.addLine(to: CGPoint(x: 239.17, y: 522.07))
        bezier65Path.addLine(to: CGPoint(x: 236.73, y: 519.09))
        bezier65Path.close()
        fillColor2.setFill()
        bezier65Path.fill()
        
        
        //// Bezier 66 Drawing
        let bezier66Path = UIBezierPath()
        bezier66Path.move(to: CGPoint(x: 187.92, y: 522.07))
        bezier66Path.addLine(to: CGPoint(x: 190.36, y: 525.06))
        bezier66Path.addLine(to: CGPoint(x: 187.92, y: 522.07))
        bezier66Path.close()
        fillColor22.setFill()
        bezier66Path.fill()
        
        
        //// Bezier 67 Drawing
        let bezier67Path = UIBezierPath()
        bezier67Path.move(to: CGPoint(x: 239.17, y: 522.07))
        bezier67Path.addLine(to: CGPoint(x: 241.61, y: 525.06))
        bezier67Path.addLine(to: CGPoint(x: 239.17, y: 522.07))
        bezier67Path.close()
        fillColor16.setFill()
        bezier67Path.fill()
        
        
        //// Bezier 68 Drawing
        let bezier68Path = UIBezierPath()
        bezier68Path.move(to: CGPoint(x: 185.48, y: 525.06))
        bezier68Path.addLine(to: CGPoint(x: 187.92, y: 528.04))
        bezier68Path.addLine(to: CGPoint(x: 185.48, y: 525.06))
        bezier68Path.close()
        fillColor10.setFill()
        bezier68Path.fill()
        
        
        //// Bezier 69 Drawing
        let bezier69Path = UIBezierPath()
        bezier69Path.move(to: CGPoint(x: 236.73, y: 525.06))
        bezier69Path.addLine(to: CGPoint(x: 239.17, y: 528.04))
        bezier69Path.addLine(to: CGPoint(x: 236.73, y: 525.06))
        bezier69Path.close()
        fillColor27.setFill()
        bezier69Path.fill()
        
        
        //// Bezier 70 Drawing
        let bezier70Path = UIBezierPath()
        bezier70Path.move(to: CGPoint(x: 190.36, y: 528.04))
        bezier70Path.addLine(to: CGPoint(x: 192.8, y: 531.02))
        bezier70Path.addLine(to: CGPoint(x: 190.36, y: 528.04))
        bezier70Path.close()
        fillColor25.setFill()
        bezier70Path.fill()
        
        
        //// Bezier 71 Drawing
        let bezier71Path = UIBezierPath()
        bezier71Path.move(to: CGPoint(x: 233.47, y: 529.03))
        bezier71Path.addCurve(to: CGPoint(x: 235.1, y: 530.03), controlPoint1: CGPoint(x: 232.39, y: 530.36), controlPoint2: CGPoint(x: 234.96, y: 530.19))
        bezier71Path.addCurve(to: CGPoint(x: 233.47, y: 529.03), controlPoint1: CGPoint(x: 236.18, y: 528.7), controlPoint2: CGPoint(x: 233.61, y: 528.87))
        bezier71Path.close()
        fillColor12.setFill()
        bezier71Path.fill()
        
        
        //// Bezier 72 Drawing
        let bezier72Path = UIBezierPath()
        bezier72Path.move(to: CGPoint(x: 187.92, y: 531.02))
        bezier72Path.addLine(to: CGPoint(x: 190.36, y: 534.01))
        bezier72Path.addLine(to: CGPoint(x: 187.92, y: 531.02))
        bezier72Path.close()
        fillColor25.setFill()
        bezier72Path.fill()
        
        
        //// Bezier 73 Drawing
        let bezier73Path = UIBezierPath()
        bezier73Path.move(to: CGPoint(x: 222.08, y: 542.96))
        bezier73Path.addLine(to: CGPoint(x: 234.29, y: 534.01))
        bezier73Path.addCurve(to: CGPoint(x: 222.08, y: 542.96), controlPoint1: CGPoint(x: 227.97, y: 533.71), controlPoint2: CGPoint(x: 226.1, y: 536.95))
        bezier73Path.close()
        fillColor5.setFill()
        bezier73Path.fill()
        
        
        //// Bezier 74 Drawing
        let bezier74Path = UIBezierPath()
        bezier74Path.move(to: CGPoint(x: 190.36, y: 534.01))
        bezier74Path.addLine(to: CGPoint(x: 192.8, y: 536.99))
        bezier74Path.addLine(to: CGPoint(x: 190.36, y: 534.01))
        bezier74Path.close()
        fillColor30.setFill()
        bezier74Path.fill()
        
        
        //// Bezier 75 Drawing
        let bezier75Path = UIBezierPath()
        bezier75Path.move(to: CGPoint(x: 192.8, y: 534.01))
        bezier75Path.addLine(to: CGPoint(x: 195.24, y: 536.99))
        bezier75Path.addLine(to: CGPoint(x: 192.8, y: 534.01))
        bezier75Path.close()
        fillColor23.setFill()
        bezier75Path.fill()
        
        
        //// Bezier 76 Drawing
        let bezier76Path = UIBezierPath()
        bezier76Path.move(to: CGPoint(x: 224.52, y: 534.01))
        bezier76Path.addLine(to: CGPoint(x: 226.96, y: 536.99))
        bezier76Path.addLine(to: CGPoint(x: 224.52, y: 534.01))
        bezier76Path.close()
        fillColor15.setFill()
        bezier76Path.fill()
        
        
        //// Bezier 77 Drawing
        let bezier77Path = UIBezierPath()
        bezier77Path.move(to: CGPoint(x: 229.4, y: 534.01))
        bezier77Path.addLine(to: CGPoint(x: 231.85, y: 536.99))
        bezier77Path.addLine(to: CGPoint(x: 229.4, y: 534.01))
        bezier77Path.close()
        fillColor14.setFill()
        bezier77Path.fill()
        
        
        //// Bezier 78 Drawing
        let bezier78Path = UIBezierPath()
        bezier78Path.move(to: CGPoint(x: 192.8, y: 536.99))
        bezier78Path.addLine(to: CGPoint(x: 195.24, y: 539.97))
        bezier78Path.addLine(to: CGPoint(x: 192.8, y: 536.99))
        bezier78Path.close()
        fillColor6.setFill()
        bezier78Path.fill()
        
        
        //// Bezier 79 Drawing
        let bezier79Path = UIBezierPath()
        bezier79Path.move(to: CGPoint(x: 195.24, y: 536.99))
        bezier79Path.addLine(to: CGPoint(x: 195.24, y: 542.96))
        bezier79Path.addLine(to: CGPoint(x: 200.12, y: 542.96))
        bezier79Path.addCurve(to: CGPoint(x: 195.24, y: 536.99), controlPoint1: CGPoint(x: 198.79, y: 538.08), controlPoint2: CGPoint(x: 199.23, y: 538.62))
        bezier79Path.close()
        fillColor31.setFill()
        bezier79Path.fill()
        
        
        //// Bezier 80 Drawing
        let bezier80Path = UIBezierPath()
        bezier80Path.move(to: CGPoint(x: 222.08, y: 536.99))
        bezier80Path.addLine(to: CGPoint(x: 224.52, y: 539.97))
        bezier80Path.addLine(to: CGPoint(x: 222.08, y: 536.99))
        bezier80Path.close()
        fillColor2.setFill()
        bezier80Path.fill()
        
        
        //// Bezier 81 Drawing
        let bezier81Path = UIBezierPath()
        bezier81Path.move(to: CGPoint(x: 226.96, y: 536.99))
        bezier81Path.addLine(to: CGPoint(x: 229.4, y: 539.97))
        bezier81Path.addLine(to: CGPoint(x: 226.96, y: 536.99))
        bezier81Path.close()
        fillColor11.setFill()
        bezier81Path.fill()
        
        
        //// Bezier 82 Drawing
        let bezier82Path = UIBezierPath()
        bezier82Path.move(to: CGPoint(x: 220.46, y: 541.96))
        bezier82Path.addCurve(to: CGPoint(x: 221.27, y: 543.95), controlPoint1: CGPoint(x: 220.32, y: 542.13), controlPoint2: CGPoint(x: 220.19, y: 545.28))
        bezier82Path.addCurve(to: CGPoint(x: 220.46, y: 541.96), controlPoint1: CGPoint(x: 221.41, y: 543.79), controlPoint2: CGPoint(x: 221.54, y: 540.64))
        bezier82Path.close()
        fillColor6.setFill()
        bezier82Path.fill()
        
        
        //// Bezier 83 Drawing
        let bezier83Path = UIBezierPath()
        bezier83Path.move(to: CGPoint(x: 224.52, y: 539.97))
        bezier83Path.addLine(to: CGPoint(x: 226.96, y: 542.96))
        bezier83Path.addLine(to: CGPoint(x: 224.52, y: 539.97))
        bezier83Path.close()
        fillColor22.setFill()
        bezier83Path.fill()
        
        
        //// Bezier 84 Drawing
        let bezier84Path = UIBezierPath()
        bezier84Path.move(to: CGPoint(x: 197.68, y: 542.96))
        bezier84Path.addLine(to: CGPoint(x: 200.12, y: 545.94))
        bezier84Path.addLine(to: CGPoint(x: 197.68, y: 542.96))
        bezier84Path.close()
        fillColor30.setFill()
        bezier84Path.fill()
        
        
        //// Bezier 85 Drawing
        let bezier85Path = UIBezierPath()
        bezier85Path.move(to: CGPoint(x: 200.12, y: 542.96))
        bezier85Path.addLine(to: CGPoint(x: 207.44, y: 554.89))
        bezier85Path.addLine(to: CGPoint(x: 219.64, y: 545.94))
        bezier85Path.addCurve(to: CGPoint(x: 209.88, y: 551.91), controlPoint1: CGPoint(x: 214.67, y: 546.06), controlPoint2: CGPoint(x: 213.53, y: 547.53))
        bezier85Path.addLine(to: CGPoint(x: 200.12, y: 542.96))
        bezier85Path.close()
        fillColor5.setFill()
        bezier85Path.fill()
        
        
        //// Bezier 86 Drawing
        let bezier86Path = UIBezierPath()
        bezier86Path.move(to: CGPoint(x: 202.56, y: 542.96))
        bezier86Path.addLine(to: CGPoint(x: 205, y: 545.94))
        bezier86Path.addLine(to: CGPoint(x: 202.56, y: 542.96))
        bezier86Path.close()
        fillColor21.setFill()
        bezier86Path.fill()
        
        
        //// Bezier 87 Drawing
        let bezier87Path = UIBezierPath()
        bezier87Path.move(to: CGPoint(x: 214.76, y: 542.96))
        bezier87Path.addLine(to: CGPoint(x: 217.2, y: 545.94))
        bezier87Path.addLine(to: CGPoint(x: 214.76, y: 542.96))
        bezier87Path.close()
        fillColor11.setFill()
        bezier87Path.fill()
        
        
        //// Bezier 88 Drawing
        let bezier88Path = UIBezierPath()
        bezier88Path.move(to: CGPoint(x: 200.12, y: 545.94))
        bezier88Path.addLine(to: CGPoint(x: 202.56, y: 548.92))
        bezier88Path.addLine(to: CGPoint(x: 200.12, y: 545.94))
        bezier88Path.close()
        fillColor2.setFill()
        bezier88Path.fill()
        
        
        //// Bezier 89 Drawing
        let bezier89Path = UIBezierPath()
        bezier89Path.move(to: CGPoint(x: 205, y: 545.94))
        bezier89Path.addLine(to: CGPoint(x: 207.44, y: 548.92))
        bezier89Path.addLine(to: CGPoint(x: 205, y: 545.94))
        bezier89Path.close()
        fillColor22.setFill()
        bezier89Path.fill()
        
        
        //// Bezier 90 Drawing
        let bezier90Path = UIBezierPath()
        bezier90Path.move(to: CGPoint(x: 209.88, y: 545.94))
        bezier90Path.addLine(to: CGPoint(x: 212.32, y: 548.92))
        bezier90Path.addLine(to: CGPoint(x: 209.88, y: 545.94))
        bezier90Path.close()
        fillColor3.setFill()
        bezier90Path.fill()
        
        
        //// Bezier 91 Drawing
        let bezier91Path = UIBezierPath()
        bezier91Path.move(to: CGPoint(x: 217.2, y: 545.94))
        bezier91Path.addLine(to: CGPoint(x: 219.64, y: 548.92))
        bezier91Path.addLine(to: CGPoint(x: 217.2, y: 545.94))
        bezier91Path.close()
        fillColor17.setFill()
        bezier91Path.fill()
        
        
        //// Bezier 92 Drawing
        let bezier92Path = UIBezierPath()
        bezier92Path.move(to: CGPoint(x: 202.56, y: 548.92))
        bezier92Path.addLine(to: CGPoint(x: 205, y: 551.91))
        bezier92Path.addLine(to: CGPoint(x: 202.56, y: 548.92))
        bezier92Path.close()
        fillColor18.setFill()
        bezier92Path.fill()
        
        
        //// Bezier 93 Drawing
        let bezier93Path = UIBezierPath()
        bezier93Path.move(to: CGPoint(x: 207.44, y: 548.92))
        bezier93Path.addLine(to: CGPoint(x: 209.88, y: 551.91))
        bezier93Path.addLine(to: CGPoint(x: 207.44, y: 548.92))
        bezier93Path.close()
        fillColor6.setFill()
        bezier93Path.fill()
        
        
        //// Bezier 94 Drawing
        let bezier94Path = UIBezierPath()
        bezier94Path.move(to: CGPoint(x: 212.32, y: 548.92))
        bezier94Path.addLine(to: CGPoint(x: 214.76, y: 551.91))
        bezier94Path.addLine(to: CGPoint(x: 212.32, y: 548.92))
        bezier94Path.close()
        bezier94Path.move(to: CGPoint(x: 205, y: 551.91))
        bezier94Path.addLine(to: CGPoint(x: 207.44, y: 554.89))
        bezier94Path.addLine(to: CGPoint(x: 205, y: 551.91))
        bezier94Path.close()
        fillColor24.setFill()
        bezier94Path.fill()
        
        
        //// Bezier 95 Drawing
        let bezier95Path = UIBezierPath()
        bezier95Path.move(to: CGPoint(x: 209.88, y: 551.91))
        bezier95Path.addLine(to: CGPoint(x: 212.32, y: 554.89))
        bezier95Path.addLine(to: CGPoint(x: 209.88, y: 551.91))
        bezier95Path.close()
        fillColor22.setFill()
        bezier95Path.fill()
        
        context.restoreGState()
        
    }
    
    
    
    
    @objc(Bg_0ResizingBehavior)
    public enum ResizingBehavior: Int {
        case aspectFit /// The content is proportionally resized to fit into the target rectangle.
        case aspectFill /// The content is proportionally resized to completely fill the target rectangle.
        case stretch /// The content is stretched to match the entire target rectangle.
        case center /// The content is centered in the target rectangle, but it is NOT resized.
        
        public func apply(rect: CGRect, target: CGRect) -> CGRect {
            if rect == target || target == CGRect.zero {
                return rect
            }
            
            var scales = CGSize.zero
            scales.width = abs(target.width / rect.width)
            scales.height = abs(target.height / rect.height)
            
            switch self {
            case .aspectFit:
                scales.width = min(scales.width, scales.height)
                scales.height = scales.width
            case .aspectFill:
                scales.width = max(scales.width, scales.height)
                scales.height = scales.width
            case .stretch:
                break
            case .center:
                scales.width = 1
                scales.height = 1
            }
            
            var result = rect.standardized
            result.size.width *= scales.width
            result.size.height *= scales.height
            result.origin.x = target.minX + (target.width - result.width) / 2
            result.origin.y = target.minY + (target.height - result.height) / 2
            return result
        }
    }
}
